at: Assign correct permissions to atd file
Source: MontaVista Software, LLC
MR: 64786
Type: Defect Fix
Disposition: Local
ChangeID: 1a18174ea7dd51103771a8b84e4cc4e4a4fdee0b
Description:
Sometimes /usr/sbin/atd file has incorrect permission set to -rwsr-sr-x,
due to which at jobs won't run properly. So assign correct permission
to /usr/sbin/atd during postinstall task.

Added bison-native and base-passwd dependency to solve below errors
respectively.

-- snip --
yacc -d parsetime.y
make: yacc: Command not found
make: *** [y.tab.c] Error 127
-- snip --

yacc command is given by bison-native recipe.

-- snip --
/usr/bin/install: invalid user 'daemon'
make: *** [install] Error 1
ERROR: oe_runmake failed
-- snip --

base-passwd populates the "etc/passwd" under target sysroot containing
necessary user names, which are then accessed by install command.

Reviewed-by: Jeremy Puhlman <jpuhlman@mvista.com>
Signed-off-by: Jagadeesh Krishnanjanappa <jkrishnanjanappa@mvista.com>
Signed-off-by: Jeremy Puhlman <jpuhlman@mvista.com>