man-db: fix mulitlib conflict issue in doc packages
Source: meta-montavista-cgx
MR: 00000
Type: Integration
Disposition: Merged from meta-montavista-cgx
ChangeID: 98ba3743a4d06e2fe95328c66844871fcfe533e2
Description:

Solves below error:
-- snip --
Error: Transaction check error:
  file /usr/share/doc/man-db/man-db-manual.ps conflicts between attempted installs of lib32-man-db-doc-2.8.3-r0.i586 and man-db-doc-2.8.3-r0.corei7_64
-- snip --

Signed-off-by: Jagadeesh Krishnanjanappa <jkrishnanjanappa@mvista.com>
Signed-off-by: Jeremy A. Puhlman <jpuhlman@mvista.com>