Fix initscripts-functions and lsbinitscripts conflict issue
Source: MontaVista Software, LLC
MR: 00000
Type: Defect Fix
Disposition: Local
ChangeID: 2da55d25e646f73a6d9b30e564717c9986254eae
Description:

Solves below conflict error:
-- snip --
Error: Transaction check error:
  file /etc/init.d/functions from install of lib32-initscripts-functions-1.0-r155.3.i586 conflicts with file from package lsbinitscripts-9.72-r0.3.core2_64
-- snip --

Signed-off-by: Jagadeesh Krishnanjanappa <jkrishnanjanappa@mvista.com>