Mask non fatal error if linux kernel version is mismatch
Source: MontaVista Software, LLC
MR: 92730
Type: Integration
Disposition: Local
ChangeID: ca8911e507a48bd5d0aa9dd86eb49e8ea6bc39e3
Description:
Perhaps in future, linux kernel source gets regular updates;
due to which the linux version in the code can change, in such case do not
throw an error if there is a mismatch between the given linux kernel
version in the recipe and the actually version.

Solves below error:
-- snip --
ERROR: linux-mvista-4.14.3+gitAUTOINC+faf180dfc3-r0 do_kernel_version_sanity_check: Package Version (4.14.3+gitAUTOINC+faf180dfc3) does not match of kernel being built (4.14.15). Please update the PV variable to match the kernel source or set KERNEL_VERSION_SANITY_SKIP="1" in your recipe.
-- snip --

Reviewed-by: Jeremy Puhlman <jpuhlman@mvista.com>
Signed-off-by: Jagadeesh Krishnanjanappa <jkrishnanjanappa@mvista.com>