Remove do_bootimg task and its dependency chain for packagegroup images
Source: MontaVista Software, LLC
MR: 71514
Type: Defect Fix
Disposition: Local
ChangeID: 853eb51904b355302c80d0c185a12f4374de9212
Description:
Since packagegroup image recipes nullify IMAGE_FSTYPES, there will be no do_image_*
tasks. Due to this, any packagegroup image recipes, which have tasks such as do_bootimg that
depend on do_image_ext4 will eventually fail as below:
-- snip --
ERROR: Task do_bootimg in
virtual:packagegroup-image:base:.../layers/meta-montavista-cgx/recipes-mvista/images/installer-image.bb
depends upon non-existent task do_image_ext4 in
virtual:packagegroup-image:base:.../layers/meta-montavista-cgx/recipes-mvista/images/installer-image.bb
-- snip --

So, remove do_bootimg and nullify dependency chain for this task for
packagegroup images.

Reviewed-by: Jeremy Puhlman <jpuhlman@mvista.com>
Signed-off-by: Jagadeesh Krishnanjanappa <jkrishnanjanappa@mvista.com>
Signed-off-by: Jeremy Puhlman <jpuhlman@mvista.com>