oprofile: fix multilib conflict issue
Source: MontaVista Software, LLC
MR: 94839
Type: Defect Fix
Disposition: Local
ChangeID: ee1e1bc65a4dc5a554416efef258118af8673eee
Description:

Re-define --mandir configure option value to solve below conflict
errors,

-- snip --
Error: Transaction check error:
  file /usr/share/man/man1/ocount.1 conflicts between attempted installs of oprofile-doc-1.1.0-r0.aarch64 and lib32-oprofile-doc-1.1.0-r0.aarch64_ilp32
  file /usr/share/man/man1/op-check-perfevents.1 conflicts between attempted installs of oprofile-doc-1.1.0-r0.aarch64 and lib32-oprofile-doc-1.1.0-r0.aarch64_ilp32
  file /usr/share/man/man1/opannotate.1 conflicts between attempted installs of oprofile-doc-1.1.0-r0.aarch64 and lib32-oprofile-doc-1.1.0-r0.aarch64_ilp32
  file /usr/share/man/man1/oparchive.1 conflicts between attempted installs of oprofile-doc-1.1.0-r0.aarch64 and lib32-oprofile-doc-1.1.0-r0.aarch64_ilp32
  file /usr/share/man/man1/operf.1 conflicts between attempted installs of oprofile-doc-1.1.0-r0.aarch64 and lib32-oprofile-doc-1.1.0-r0.aarch64_ilp32
  file /usr/share/man/man1/opgprof.1 conflicts between attempted installs of oprofile-doc-1.1.0-r0.aarch64 and lib32-oprofile-doc-1.1.0-r0.aarch64_ilp32
  file /usr/share/man/man1/ophelp.1 conflicts between attempted installs of oprofile-doc-1.1.0-r0.aarch64 and lib32-oprofile-doc-1.1.0-r0.aarch64_ilp32
  file /usr/share/man/man1/opimport.1 conflicts between attempted installs of oprofile-doc-1.1.0-r0.aarch64 and lib32-oprofile-doc-1.1.0-r0.aarch64_ilp32
  file /usr/share/man/man1/opreport.1 conflicts between attempted installs of oprofile-doc-1.1.0-r0.aarch64 and lib32-oprofile-doc-1.1.0-r0.aarch64_ilp32
  file /usr/share/man/man1/oprofile.1 conflicts between attempted installs of oprofile-doc-1.1.0-r0.aarch64 and lib32-oprofile-doc-1.1.0-r0.aarch64_ilp32
-- snip --

V2 Changes
 * Update man.conf to parse man pages under /usr/share/man/* and /usr/share/*/man
   directories.

Reviewed-by: Jeremy Puhlman <jpuhlman@mvista.com>
Signed-off-by: Jeremy Puhlman <jpuhlman@mvista.com>
Signed-off-by: Jagadeesh Krishnanjanappa <jkrishnanjanappa@mvista.com>