ltt-kdump: Fix print syntax errors
Source: MontaVista Software, LLC
MR: 93798
Type: Defect Fix
Disposition: Local
Description:

Fix the following (and similar) errors.

File
"meta-montavista-cgx/recipes-kernel/lttng-2.0/ltt-kdump-0.2/sources/ltt.py",
line 360
    print "    subbuf size = %d (pad %d) %d" % (padded_size,
                                           ^
SyntaxError: invalid syntax

File
"meta-montavista-cgx/recipes-kernel/lttng-2.0/ltt-kdump-0.2/sources/ltt.py",
line 394
    print "  subbuffer %d" % subbuf_num
                         ^
SyntaxError: Missing parentheses in call to 'print'

Signed-off-by: Silesh C V <svellattu@mvista.com>
Reviewed-by: Corey Minyard <cminyard@mvista.com>
Signed-off-by: Jagadeesh Krishnanjanappa <jkrishnanjanappa@mvista.com>