Assign empty value to ROOTFS_PKGMANAGE_BOOTSTRAP to solve yocto check layer error
Source: meta-montavista-cgx-github
MR: 00000
Type: Integration
Disposition: Merged from meta-montavista-cgx-github
ChangeID: 13900f6c01027fc3d49752a80fbe52a76da77711
Description:

Solves:
-- snip --
ERROR: Nothing RPROVIDES '${ROOTFS_PKGMANAGE_BOOTSTRAP}' (but virtual:packagegroup-image:base:/opt/work_jagadeesh/openx-build_0104/openx-build/bsp-build-xilinx/opencgx-xilinx-2.6/project/../layers/meta-security/recipes-security/images/security-server-image.bb, virtual:packagegroup-image:base:/opt/work_jagadeesh/openx-build_0104/openx-build/bsp-build-xilinx/opencgx-xilinx-2.6/project/../layers/meta-security/recipes-security/images/security-client-image.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target '${ROOTFS_PKGMANAGE_BOOTSTRAP}' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['${ROOTFS_PKGMANAGE_BOOTSTRAP}']
ERROR: Required build target 'meta-world-pkgdata' has no buildable providers.
Missing or unbuildable dependency chain was: ['meta-world-pkgdata', 'packagegroup-security-server-image', '${ROOTFS_PKGMANAGE_BOOTSTRAP}']
-- snip --

Signed-off-by: Jagadeesh Krishnanjanappa <jkrishnanjanappa@mvista.com>
Signed-off-by: Jeremy Puhlman <jpuhlman@mvista.com>