Changes to build cgx-complete-image for stratix10
Source: meta-montavista-cgx
MR: 00000
Type: Integration
Disposition: Merged from meta-montavista-cgx
ChangeID: 0dc74cc0640775180620039dc72cc1555a0f1733
Description:

1. Prefer building u-boot-socfpga v2019.01 recipe, as v2017.09 recipe
does not compile (fails with below error) with dtc v1.4.7 (present in thud).

-- snip --
In file included from .../u-boot-socfpga/v2017.09+gitAUTOINC+53ce6e587a-r0/git/tools/../lib/libfdt/libfdt.h:10:0,
                 from .../u-boot-socfpga/v2017.09+gitAUTOINC+53ce6e587a-r0/git/tools/../include/libfdt.h:1,
                 from .../u-boot-socfpga/v2017.09+gitAUTOINC+53ce6e587a-r0/git/tools/fdt_host.h:11,
                 from .../u-boot-socfpga/v2017.09+gitAUTOINC+53ce6e587a-r0/git/tools/mkimage.h:22,
                 from .../u-boot-socfpga/v2017.09+gitAUTOINC+53ce6e587a-r0/git/tools/../common/bootm.c:26,
                 from tools/common/bootm.c:1:
.../u-boot-socfpga/v2017.09+gitAUTOINC+53ce6e587a-r0/recipe-sysroot-native/usr/include/libfdt_env.h:71:30: error: conflicting types for ‘fdt64_t’
 typedef uint64_t FDT_BITWISE fdt64_t;
                              ^~~~~~~
In file included from <command-line>:0:0:
.../u-boot-socfpga/v2017.09+gitAUTOINC+53ce6e587a-r0/git/include/libfdt_env.h:19:16: note: previous declaration of ‘fdt64_t’ was here
 typedef __be64 fdt64_t;
                ^~~~~~~
In file included from .../u-boot-socfpga/v2017.09+gitAUTOINC+53ce6e587a-r0/git/include/libfdt_env.h:12:0,
                 from <command-line>:0:
.../u-boot-socfpga/v2017.09+gitAUTOINC+53ce6e587a-r0/recipe-sysroot-native/usr/include/libfdt_env.h:91:24: error: expected ‘)’ before ‘x’
 static inline uint32_t fdt32_to_cpu(fdt32_t x)
                        ^
.../u-boot-socfpga/v2017.09+gitAUTOINC+53ce6e587a-r0/git/include/compiler.h:71:9: error: expected ‘)’ before ‘&’ token
  ((((x) & 0xff000000) >> 24) | \
         ^
-- snip --

2. Alter SPL_BINARY, UBOOT_BINARY and IMAGE_BOOT_FILES values to solve
below errors.

-- snip --
| cp: cannot stat '.../u-boot-socfpga/v2019.01+gitAUTOINC+d3689267f9-r0/build/socfpga_stratix10_defconfig/u-boot-dtb.img': No such file or directory

...

| aarch64-montavista-linux-objcopy: '.../u-boot-socfpga/v2019.01+gitAUTOINC+d3689267f9-r0/build/socfpga_stratix10_defconfig/spl/u-boot-spl-dtb.bin': No such file or directory

...

| ERROR: _exec_cmd: install -m 0644 -D ...tmp/deploy/images/stratix10/u-boot-dtb.img .../cgx-complete-image/1.0-r0/deploy-cgx-complete-image-image-complete/cgx-complete-image-stratix10-20190514103144/tmp.wic.i9gsccar/boot.1/u-boot-dtb.img returned '1' instead of 0
| output: install: cannot stat '...tmp/deploy/images/stratix10/u-boot-dtb.img': No such file or directory
-- snip --

Signed-off-by: Jagadeesh Krishnanjanappa <jkrishnanjanappa@mvista.com>
Signed-off-by: Jeremy Puhlman <jpuhlman@mvista.com>