lttng-modules: Backport Linux 5.18+, 5.15.44+, 5.10.119+ fixes
Source: meta-montavista-cgx
MR: 120339
Type: Security Fix
Disposition: Merged from meta-montavista-cgx
ChangeID: 2671fa4d401d955c388dace757a432e5abed956b
Description:

The Linux kernel commit 14c174633f349 ("random: remove unused tracepoints")
removed unused tracepoints and has been backported to stable Linux kernel
releases. This causes build failure of lttng-modules:

"
lttng-modules-2.11.6/probes/lttng-probe-random.c:18:10: fatal error: trace/events/random.h: No such file or directory
|    18 | #include <trace/events/random.h>
|       |          ^~~~~~~~~~~~~~~~~~~~~~~
| compilation terminated.
"

Backport patches from lttng-modules master branch to address the build
failure on all of Linux 5.18.y, 5.15.y 5.10.y, 5.4, 4.19, 4.14, and 4.9 kernel versions.

(From OE-Core rev: 9f301f5563df868626d624c2d0781dae1b81a4c0)

Signed-off-by: Marek Vasut <marex@denx.de>
Cc: Bruce Ashfield <bruce.ashfield@gmail.com>
Cc: Steve Sakoman <steve@sakoman.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>
(cherry picked from commit d2f8a57a30066815aba9cd4ebef7bf9edf21bcaa)
[Fix up for Rocko context]
Signed-off-by: Armin Kuster <akuster@mvista.com>
Reviewed-by:  Jeremy Puhlman <jpuhlman@mvista.com>
Signed-off-by: Armin Kuster <akuster@mvista.com>
Signed-off-by: Jeremy A. Puhlman <jpuhlman@mvista.com>