libunwind: fix conflict error due to mlib libunwind.h
Source: MontaVista Software, LLC
MR: 92741
Type: Defect Fix
Disposition: Needs submitting to OE-core
ChangeID: 77494d9365be6f444587de7d44a9f9d764ff89ac
Description:
Solves below error:
-- snip --
Error: Transaction check error: file /usr/include/libunwind.h conflicts between attempted installs of lib32-libunwind-dev-1.2-r0.1.i586 and libunwind-dev-1.2-r0.1.core2_64
-- snip --

Signed-off-by: Jagadeesh Krishnanjanappa <jkrishnanjanappa@mvista.com>