mvl-support: remove redundant do_compile task
Source: MontaVista Software, LLC
MR: 00000
Type: Defect Fix
Disposition: Local
Description:
The ${DATETIME} in the do_compile task is unique every second, this makes
the mvl-support to rebuild every time it is called to build. This causes will
below
message:

-- snip --
ERROR: mvl-support-1.0-2.2.0 do_compile: Taskhash mismatch aff5d7869c7c12fd99399eef7f12fcb9 versus e67634285bba5edc91be1b0606c99848 for /CGE7_SHDD/qemux86-64-4.1-2.2-161011094003/qemux86-64-4.1-2.2-project/layers/meta-montavista-cgx/recipes-mvista/mvl-support/mvl-support.bb.do_compile
-- snip --

Since do_compile[nostamps] = "1" will exactly do the same job; hence removing
redundant do_compile task. Also, this solves the above error message.

Signed-off-by: Jagadeesh Krishnanjanappa <jkrishnanjanappa@mvista.com>