python3: Specify _host_cpu as armeb while cross-compiling for armeb
Source: MontaVista Software, LLC
MR: 98896
Type: Defect Fix
Disposition: Needs submitting to openembedded-core layer
ChangeID: 72850b8d74e7b7293ed47b76759b3e1c9f6b6114
Description:

It solves generating incorrect SOABI names of type
cpython-35m-x86_64-linux-gnu.so under /usr/lib/python3.5/lib-dynload.
Due to which 'dnf --version' fails with the following error on
armeb target.

-- snip --
(prompt) # dnf --version
Traceback (most recent call last):
  File "/usr/bin/dnf", line 57, in <module>
    from dnf.cli import main
  File "/usr/lib/python3.5/site-packages/dnf/__init__.py", line 23, in <module>
    import dnf.exceptions
  File "/usr/lib/python3.5/site-packages/dnf/exceptions.py", line 21, in <module>
    from dnf.i18n import ucd
  File "/usr/lib/python3.5/site-packages/dnf/i18n.py", line 22, in <module>
    from dnf.pycomp import unicode
  File "/usr/lib/python3.5/site-packages/dnf/pycomp.py", line 21, in <module>
    from gettext import NullTranslations
  File "/usr/lib/python3.5/gettext.py", line 49, in <module>
    import locale, copy, io, os, re, struct, sys
  File "/usr/lib/python3.5/struct.py", line 13, in <module>
    from _struct import *
ImportError: No module named '_struct'
-- snip --

With this change SOABI name generated will be of type
*cpython-35m-armeb-linux-gnueabihf.so.

Reviewed-by: Jeremy Puhlman <jpuhlman@mvista.com>
Signed-off-by: Jagadeesh Krishnanjanappa <jkrishnanjanappa@mvista.com>