rpm: define EM_AARCH64 for debugedit
Source: MontaVista Software, LLC
MR: 62010
Type: Defect Fix
Disposition: Backport from OE-core
Description:
EM_AARCH64 maybe not be defined due to old version
elf.h when compile rpm-native, and lead to that
debugedit can not work on aarch64 elf object
files, since there is no other dependence, except
these two macro, define them to make debugedit work
on aarch64 elf files.

error snippet:
-- snip --
ERROR: debugedit failed with exit code 256 (cmd was '/local/jenkins/qemuarm64-4.1-2.0-151208042443/qemuarm64-4.1-2.0-project/tmp/sysroots/x86_64-linux/usr/lib/rpm/bin/debugedit' -b '/local/jenkins/qemuarm64-4.1-2.0-151208042443/qemuarm64-4.1-2.0-project/tmp/work/aarch64-montavista-linux' -d '/usr/src/debug' -i -l '/local/jenkins/qemuarm64-4.1-2.0-151208042443/qemuarm64-4.1-2.0-project/tmp/work/aarch64-montavista-linux/libvirt/1.2.19-r1/debugsources.list' '/local/jenkins/qemuarm64-4.1-2.0-151208042443/qemuarm64-4.1-2.0-project/tmp/work/aarch64-montavista-linux/libvirt/1.2.19-r1/package/usr/lib/libvirt/ptest/src/.libs/libvirt_driver_la-libvirt-host.o'): /local/jenkins/qemuarm64-4.1-2.0-151208042443/qemuarm64-4.1-2.0-project/tmp/sysroots/x86_64-linux/usr/lib/rpm/bin/debugedit: /local/jenkins/qemuarm64-4.1-2.0-151208042443/qemuarm64-4.1-2.0-project/tmp/work/aarch64-montavista-linux/libvirt/1.2.19-r1/package/usr/lib/libvirt/ptest/src/.libs/libvirt_driver_la-libvirt-host.o: Unhandled relocation 258 in .debug_info section
ERROR: Function failed: split_and_strip_files
-- CUT --

Reviewed-by: Jeremy Puhlman <jpuhlman@mvista.com>
Signed-off-by: Roy Li <rongqing.li@windriver.com>
Signed-off-by: Jagadeesh Krishnanjanappa <jkrishnanjanappa@mvista.com>