python3-twisted: Remove redundant RDEPENDS on python3-twisted-src
Source: meta-montavista-cgx
MR: 00000
Type: Integration
Disposition: Merged from meta-montavista-cgx
ChangeID: 027d3f41f92bea3aca65b00f3a9469d951acfc5c
Description:

The /usr/lib64/python3.5/site-packages/twisted/scripts/twistd.py
(previously provided by python3-twisted-src) is now provided
by python3-twisted-core package, which is already pulled in by
python3-twisted package.

It solves yocto-check-layer error:
-- snip --
ERROR: Nothing RPROVIDES 'python3-twisted-src' (but /opt/work_jagadeesh/openx-build_0104/openx-build/bsp-build-xilinx/opencgx-xilinx-2.6/project_new/../layers/meta-openembedded/meta-python/recipes-devtools/python/python3-twisted_18.4.0.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'python3-twisted-src' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['python3-twisted-src']
ERROR: Required build target 'meta-world-pkgdata' has no buildable providers.
Missing or unbuildable dependency chain was: ['meta-world-pkgdata', 'python3-twisted', 'python3-twisted-src']
-- snip --

Signed-off-by: Jagadeesh Krishnanjanappa <jkrishnanjanappa@mvista.com>
Signed-off-by: Jeremy Puhlman <jpuhlman@mvista.com>