Add required BBFILES_DYNAMIC to solve below yocto layers check
Source: meta-montavista-cgx-github
MR: 00000
Type: Integration
Disposition: Merged from meta-montavista-cgx-github
ChangeID: 4de316729715f43ed233081bfe72548206c77a0a
Description:

-- snip --
ERROR: Nothing RPROVIDES 'memcached' (but /opt/work_jagadeesh/openx-build_0104/openx-build/bsp-build-xilinx/opencgx-xilinx-2.6/project/../layers/meta-cloud-services/meta-openstack/recipes-devtools/python/python-horizon_git.bb RDEPENDS on or otherwise requires it)
memcached was skipped: incompatible with host aarch64-montavista-linux (not in COMPATIBLE_HOST)
memcached was skipped: incompatible with host aarch64-montavista-linux (not in COMPATIBLE_HOST)
NOTE: Runtime target 'memcached' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['memcached']
ERROR: Required build target 'meta-world-pkgdata' has no buildable providers.
Missing or unbuildable dependency chain was: ['meta-world-pkgdata', 'python-horizon', 'memcached']
-- snip --

-- snip --
ERROR: Nothing PROVIDES 'syslinux' (but /opt/work_jagadeesh/openx-build_0104/openx-build/bsp-build-xilinx/opencgx-xilinx-2.6/project/../layers/meta-virtualization/recipes-extended/ipxe/ipxe_git.bb DEPENDS on or otherwise requires it)
syslinux was skipped: incompatible with host aarch64-montavista-linux (not in COMPATIBLE_HOST)
ERROR: Required build target 'lib32-meta-world-pkgdata' has no buildable providers.
Missing or unbuildable dependency chain was: ['lib32-meta-world-pkgdata', 'meta-world-pkgdata', 'ipxe', 'syslinux']
-- snip --

-- snip --
ERROR: Nothing RPROVIDES 'openvswitch-controller' (but virtual:packagegroup-image:base:/opt/work_jagadeesh/openx-build_0104/openx-build/bsp-build-xilinx/opencgx-xilinx-2.6/project/../layers/meta-virtualization/recipes-extended/images/cloud-image-controller.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'openvswitch-controller' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['openvswitch-controller']
ERROR: Required build target 'meta-world-pkgdata' has no buildable providers.
Missing or unbuildable dependency chain was: ['meta-world-pkgdata', 'packagegroup-cloud-image-controller', 'openvswitch-controller']
-- snip --

-- snip --
ERROR: Nothing RPROVIDES 'ovmf-shell-efi' (but virtual:packagegroup-image:base:/opt/work_jagadeesh/openx-build_0104/openx-build/bsp-build-xilinx/opencgx-xilinx-2.6/project/../layers/poky/meta/recipes-core/ovmf/ovmf-shell-image.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'ovmf-shell-efi' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ovmf-shell-efi']
ERROR: Required build target 'meta-world-pkgdata' has no buildable providers.
Missing or unbuildable dependency chain was: ['meta-world-pkgdata', 'packagegroup-ovmf-shell-image', 'ovmf-shell-efi']
-- snip --

Signed-off-by: Jagadeesh Krishnanjanappa <jkrishnanjanappa@mvista.com>
Signed-off-by: Jeremy Puhlman <jpuhlman@mvista.com>