libdnet: Pack binary files under separate package.
Pack binary files in a separate package called ${PN}-bin. This
solves below conflict error:
-- snip --
Error: Transaction check error:
  file /usr/bin/dnet-config conflicts between attempted installs of libdnet-1.12-r0.corei7_64 and lib32-libdnet-1.12-r0.i586
-- snip --

Signed-off-by: Jagadeesh Krishnanjanappa <jkrishnanjanappa@mvista.com>