ipxe: Fix build error due to not finding lzma.h and liblzma
Source: meta-montavista-cgx
MR: 00000
Type: Integration
Disposition: Merged from meta-montavista-cgx
ChangeID: 4f56d0df4d2fd0b72aae72fabf566243507a31d2
Description:

It solves below error:
-- snip --
  [VERSION] bin/version.ipxe.pxe.o
util/zbin.c:7:18: fatal error: lzma.h: No such file or directory
compilation terminated.
make: *** [Makefile.housekeeping:1382: util/zbin] Error 1
make: *** Waiting for unfinished jobs....
  [VERSION] bin/version.undionly.kpxe.o
-- snip --

Signed-off-by: Jagadeesh Krishnanjanappa <jkrishnanjanappa@mvista.com>
Signed-off-by: Jeremy Puhlman <jpuhlman@mvista.com>