tzdata: Resolve multilib conflict errors
Source: meta-montavista-cgx
MR: 00000
Type: Integration
Disposition: Merged from meta-montavista-cgx
ChangeID: 93f16c3a38602e4cd71dabf86e10ac482d72849f
Description:

-- snip --
Error: Transaction check error:
  file /usr/share/zoneinfo/Asia/Bangkok conflicts between attempted installs of tzdata-2018g-r0.corei7_64 and lib32-tzdata-2018g-r0.i586
  file /usr/share/zoneinfo/Asia/Dubai conflicts between attempted installs of tzdata-2018g-r0.corei7_64 and lib32-tzdata-2018g-r0.i586
  file /usr/share/zoneinfo/Asia/Ashgabat conflicts between attempted installs of lib32-tzdata-asia-2018g-r0.i586 and tzdata-asia-2018g-r0.corei7_64
  file /usr/share/zoneinfo/Asia/Ashkhabad conflicts between attempted installs of lib32-tzdata-asia-2018g-r0.i586 and tzdata-asia-2018g-r0.corei7_64
  file /usr/share/zoneinfo/Asia/Ho_Chi_Minh conflicts between attempted installs of lib32-tzdata-asia-2018g-r0.i586 and tzdata-asia-2018g-r0.corei7_64
  file /usr/share/zoneinfo/Asia/Muscat conflicts between attempted installs of lib32-tzdata-asia-2018g-r0.i586 and tzdata-asia-2018g-r0.corei7_64
  file /usr/share/zoneinfo/Asia/Phnom_Penh conflicts between attempted installs of lib32-tzdata-asia-2018g-r0.i586 and tzdata-asia-2018g-r0.corei7_64
  file /usr/share/zoneinfo/Asia/Saigon conflicts between attempted installs of lib32-tzdata-asia-2018g-r0.i586 and tzdata-asia-2018g-r0.corei7_64
  file /usr/share/zoneinfo/Asia/Vientiane conflicts between attempted installs of lib32-tzdata-asia-2018g-r0.i586 and tzdata-asia-2018g-r0.corei7_64
  file /usr/include/syslog-ng/syslog-ng-config.h conflicts between attempted installs of syslog-ng-dev-3.16.1-r0.corei7_64 and lib32-syslog-ng-dev-3.16.1-r0.i586
-- snip --

Signed-off-by: Jagadeesh Krishnanjanappa <jkrishnanjanappa@mvista.com>
Signed-off-by: Jeremy Puhlman <jpuhlman@mvista.com>