dbus: solve conflict error while installing multilib package
Source: MontaVista Software, LLC
MR: 67318
Type: Defect Fix
Disposition: Local
ChangeID: 3b5a9c6e35179af51f8ab17f69b1805fef6b8635
Description:

Solved below error,
warning: Removing dbus-1.8.20-r0@lib32_i586 due to file /etc/dbus-1/system.conf conflicting with dbus-1.8.20-r0@corei7_64
error: dbus-dev-1.8.20-r0 requires lib32-dbus = 1.8.20-r0

Reviewed-by: Jeremy Puhlman <jpuhlman@mvista.com>
Signed-off-by: Jagadeesh Krishnanjanappa <jkrishnanjanappa@mvista.com>
Signed-off-by: Jeremy Puhlman <jpuhlman@mvista.com>