libgudev: Remove redundant RCONFLICTS on systemd
Source: MontaVista Software, LLC
MR: 72562
Type: Defect Fix
Disposition: Local
ChangeID: 9c73f35033ed080d8ef807d04c486202831003dc
Description:
Since the version of systemd in OE-core's Morty branch is v230; there
is no need to specify explicit RCONFLICTS on systemd (<= 220) in the
libgudev recipe. Hence removing RCONFLICTS list, as libgudev and systemd
rpms can co-exist from v230 onwards.

Fixes below error:
-- snip --
Computing transaction...error: Can't install gst-player-0.0.1+git0+ea90e63c10-r0@lib32_i586: all packages providing gstreamer1.0-plugins-good-meta failed to install:
error: Can't install gstreamer1.0-plugins-good-meta-1.8.3-r0@corei7_64: all packages providing gstreamer1.0-plugins-good-video4linux2 failed to install:
error: Can't install
gstreamer1.0-plugins-good-video4linux2-1.8.3-r0@corei7_64: unable to install provider for libgudev >= 230:
error:     libgudev-230-r0@corei7_64 conflicts with systemd-1:230+git0+3a74d4fc90-r0@corei7_64
error:     libgudev-230-r0@corei7_64 conflicts with systemd-1:230+git0+3a74d4fc90-r0@corei7_64
error:     libgudev-230-r0@lib32_i586 conflicts with systemd-1:230+git0+3a74d4fc90-r0@corei7_64
error: Can't install gstreamer1.0-plugins-good-video4linux2-1.8.3-r0@lib32_i586: unable to install provider for lib32-libgudev >= 230:
error:     libgudev-230-r0@lib32_i586 conflicts with systemd-1:230+git0+3a74d4fc90-r0@corei7_64
error: Can't install gstreamer1.0-plugins-good-video4linux2-1.8.3-r0@lib32_i586: unable to install provider for lib32-libgudev >= 230:
error:     libgudev-230-r0@lib32_i586 conflicts with systemd-1:230+git0+3a74d4fc90-r0@corei7_64
-- snip --

Signed-off-by: Jagadeesh Krishnanjanappa <jkrishnanjanappa@mvista.com>
Signed-off-by: Jeremy Puhlman <jpuhlman@mvista.com>