Update u-boot to 2019.04 and add preferred version for mvista-base profile
Source: meta-montavista-cgx
MR: 00000
Type: Integration
Disposition: Merged from meta-montavista-cgx
ChangeID: d0c87b88a8f6245a7406713ae8d241ed21d57ce0
Description:

1. The meta-riscv layer has u-boot_2019.04.bbappend, which adds
dozen of patches to support riscv targets. They also solve below
error while building u-boot for freedom-u540,

-- snip --
| scripts/kconfig/conf  --defconfig=arch/../configs/sifive_fu540_defconfig Kconfig
| ***
| *** Can't find default configuration "arch/../configs/sifive_fu540_defconfig"!
| ***
| make[2]: *** [/opt/work_jagadeesh/speed_bsps/opencgx-riscv-2.6/project/tmp/work/freedom_u540-montavista-linux/u-boot/1_2019.01-r0/git/scripts/kconfig/Makefile:128: sifive_fu540_defconfig] Error 1
-- snip --

2. Add riscv.inc to make sure u-boot-tools-native provides
u-boot-mkimage-native, when meta-riscv layer is included.
This is required as u-boot_2019.04.bbappend (from
meta-riscv) adds u-boot-tools-native dependency, due to which
both u-boot-tools-native and u-boot-mkimage-native are tried to build;
resulting in a below error:

-- snip --
ERROR: Multiple .bb files are due to be built which each provide u-boot-mkimage-native:                                  | ETA:  0:00:04
  virtual:native:/opt/work_jagadeesh/speed_bsps/opencgx-riscv-2.6/project/../layers/meta-montavista-cgx/recipes-bsp/u-boot/u-boot-tools_2019.04.bb
  virtual:native:/opt/work_jagadeesh/speed_bsps/opencgx-riscv-2.6/project/../layers/poky/meta/recipes-bsp/u-boot/u-boot-mkimage_2018.07.bb
-- snip --

Signed-off-by: Jagadeesh Krishnanjanappa <jkrishnanjanappa@mvista.com>
Signed-off-by: Jeremy A. Puhlman <jpuhlman@mvista.com>