libvirt: fix mulitlib conflict issue in doc packages
Source: meta-montavista-cgx
MR: 00000
Type: Integration
Disposition: Merged from meta-montavista-cgx
ChangeID: eda00fd12e6223591e95868195b3f9d418161ec7
Description:

Solves:
-- snip --
Error: Transaction check error:
 file /usr/share/doc/libvirt-4.7.0/html/acl.html conflicts between attempted installs of libvirt-doc-4.7.0-r0.3.corei7_64 and lib32-libvirt-doc-4.7.0-r0.3.i586
-- snip --

Signed-off-by: Jagadeesh Krishnanjanappa <jkrishnanjanappa@mvista.com>
Signed-off-by: Jeremy Puhlman <jpuhlman@mvista.com>