Include quagga-watchquagga only when sysvinit is enabled
Source: MontaVista Software, LLC
MR: 72279
Type: Defect Fix
Disposition: Local
ChangeID: c891e47395af37630ad2e5bd5ae3221d7c246240
Description:

quagga-watchquagga package is not generated when systemd is enabled.
Adding explicit RDEPENDS on quagga-watchquagga causes below error
-- snip --
ERROR: Required build target 'cgx-complete-image' has no buildable
providers.
Missing or unbuildable dependency chain was: ['cgx-complete-image',
'packagegroup-profile-base', 'packagegroup-additional-oe-tools',
'quagga-watchquagga']
-- snip --

Reviewed-by: Jeremy Puhlman <jpuhlman@mvista.com>
Signed-off-by: Jagadeesh Krishnanjanappa <jkrishnanjanappa@mvista.com>
Signed-off-by: Jeremy Puhlman <jpuhlman@mvista.com>