ltt-kdump: Fix print syntax errors
Source: meta-montavista-cgx
MR: 93798, 00000
Type: Integration
Disposition: Merged from meta-montavista-cgx
ChangeID: e660279887def9de54359a99ed5918a091bc8a77
Description:

Fix the following (and similar) errors.

File
"meta-montavista-cgx/recipes-kernel/lttng-2.0/ltt-kdump-0.2/sources/ltt.py",
line 360
    print "    subbuf size = %d (pad %d) %d" % (padded_size,
                                           ^
SyntaxError: invalid syntax

File
"meta-montavista-cgx/recipes-kernel/lttng-2.0/ltt-kdump-0.2/sources/ltt.py",
line 394
    print "  subbuffer %d" % subbuf_num
                         ^
SyntaxError: Missing parentheses in call to 'print'

Signed-off-by: Silesh C V <svellattu@mvista.com>
Reviewed-by: Corey Minyard <cminyard@mvista.com>
Signed-off-by: Jagadeesh Krishnanjanappa <jkrishnanjanappa@mvista.com>
Signed-off-by: Jeremy Puhlman <jpuhlman@mvista.com>