alltasks: fix yocto-check-layer error
Source: meta-montavista-cgx
MR: 00000
Type: Integration
Disposition: Merged from meta-montavista-cgx
ChangeID: b7441c088dbc0a52dcf1d36ac0fabe52351b704f
Description:

Solves:
-- snip --
ERROR: Nothing PROVIDES 'packagegroup-core-qt' (but /opt/work_jagadeesh/openx-build_0104/openx-build/bsp-build-xilinx/opencgx-xilinx-2.6/project_new/../layers/meta-montavista-cgx/recipes-mvista/meta/alltasks.bb DEPENDS on or otherwise requires it). Close matches:
  packagegroup-core-boot
  packagegroup-core-x11
  packagegroup-core-sdk
ERROR: Required build target 'meta-world-pkgdata' has no buildable providers.
Missing or unbuildable dependency chain was: ['meta-world-pkgdata', 'alltasks', 'packagegroup-core-qt']
-- snip --

Include packagegroup-core-qt only when meta-qt4 is included.

Signed-off-by: Jagadeesh Krishnanjanappa <jkrishnanjanappa@mvista.com>
Signed-off-by: Jeremy Puhlman <jpuhlman@mvista.com>