pmdk: depend on coreutils-native
Source: meta-montavista-cgx
MR: 124430
Type: Security Fix
Disposition: Merged from meta-montavista-cgx
ChangeID: 073d3dcda748e046962228ece59896ab504edb6f
Description:

Fix error:
install
/bin/sh: realpath: command not found
basename: missing operand
Try 'basename --help' for more information.
ERROR: oe_runmake failed
src/version.inc:46: *** Can't evaluate version.  Stop.

Signed-off-by: Jeremy A. Puhlman <jpuhlman@mvista.com>