matchbox-desktop: fix build error
The error:
-- snip --
| ../../git/libtaku/launcher-util.c:25:10: fatal error: gdk/gdkx.h: No such file or directory
|  #include <gdk/gdkx.h>
|           ^~~~~~~~~~~~
| compilation terminated.
| make[2]: *** [Makefile:394: launcher-util.o] Error 1
| make[2]: *** Waiting for unfinished jobs....
-- snip --

To fix the above error, we need to build gtk+3 with "--enable-x11-backend",
but
As DISTRO_FEATURES contains wayland, the
meta-freescale/recipes-graphics/gtk+/gtk+3_%.bbappend removes 'x11'; due to
which we get above error. Since adding/appending 'x11' in PACKAGECONFIG
removes x11 via PACKAGECONFIG_remove_imxgpu2d; we need to add it via
EXTRA_OECONF variable.

Signed-off-by: Jagadeesh Krishnanjanappa <jkrishnanjanappa@mvista.com>
Signed-off-by: Jeremy Puhlman <jpuhlman@mvista.com>