swig: use pkg-config to find libpcre cflags and libs instead of pcre-config
Source: MontaVista Software, LLC
MR: 00000
Type: Defect Fix
Disposition: Needs submitting to oe-core
ChangeID: 5f6492158c8a1460b64d30d9d1eed40c3b22b55d
Description:
This solves the below non-fatal error message during do_configure task:
-- snip --
ERROR: /usr/bin/pcre-config should not be used, use an alternative such as pkg-config
ERROR: /usr/bin/pcre-config should not be used, use an alternative such as pkg-config
-- snip --

But our 'logread' tool marks it as failure.

Signed-off-by: Jagadeesh Krishnanjanappa <jkrishnanjanappa@mvista.com>