dnf: Add armeb arch list to solve unknown "arch" error
Source: meta-montavista-cgx
MR: 98896
Type: Integration
Disposition: Merged from meta-montavista-cgx
ChangeID: 7ec14f0107f0b6205d2b0ad738cc0d324c5f742c
Description:

The armeb architecture list is missing in _BASEARCH_MAP, due to
which the following error is observed on armeb targets.

-- snip --
(prompt) # dnf --version
Error: Incorrect or unknown "arch": armv7b
-- snip --

This patch fixes the issue.

Reviewed-by: Jeremy Puhlman <jpuhlman@mvista.com>
Signed-off-by: Jagadeesh Krishnanjanappa <jkrishnanjanappa@mvista.com>
Signed-off-by: Jeremy Puhlman <jpuhlman@mvista.com>