Redefine QEMU_TARGETS list for mx8 to remove riscv32 riscv64
Source: meta-montavista-cgx
MR: 00000
Type: Integration
Disposition: Merged from meta-montavista-cgx
ChangeID: c0357fa3cb7abb9450fa83e3c2f02f6a23469a89
Description:

The qemu-qoriq recipe does not support building riscv architectures,
solves below error:

-- snip --
ERROR: Unknown target name 'riscv32-linux-user'
-- snip --

Signed-off-by: Jagadeesh Krishnanjanappa <jkrishnanjanappa@mvista.com>
Signed-off-by: Jeremy Puhlman <jpuhlman@mvista.com>
Signed-off-by: Jeremy A. Puhlman <jpuhlman@mvista.com>